### ISSUE TITLE
quartz-mongodb deprecated and unavailable, preventing build

### ISSUE THREAD

**Issue by elyazzi** [asteriskiry/eventsignup_backend#37]
See https://github.com/michaelklishin/quartz-mongodb

**Comment by aegan123** [comment]
The repo where the artifact was hosted has been taken [offline](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) and the project has been archived.

**Comment by aegan123** [comment]
There are two ways to fix this either find a new scheduler that works with mongodb or migrate to a sql database.
